/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package projeto;

import projeto.rotas.Pessoas.*;
import spark.Spark;
//MISSÕES DA AULA: 1:17:10 || 29/11 1:02:00
public class App {
    
    public static void main(String[] args) {


        Spark.port(8080);
        Spark.get("/api/pessoas", GetPessoas.GET_PESSOAS);
        Spark.post("/api/pessoas", PostPessoas.POST_PESSOAS);
        Spark.post("/api/pessoas/deletar",DeletePessoas.DELETE_PESSOA);
        Spark.post("/api/pessoas/atualizar",AtualizaPessoas.ATUALIZA_PESSOA);
        

        //Ler e entender um JSON? o que é?onde vivem? R:Facilitar a 
        //Ler sobre o princípio: Separation of Concerns
        //fazer o PessoaService adquirir informações do banco para retornar uma lista de Pessoas(entidade).
            //TODO:
            //Fazer o save pessoa funcionar
            //fazer atualizar e excluir(crud)

        // crud-> PessoaRepository=> PessoaService=> RoutePessoas(get,post,delete,update)=>app
    }
}
